import ampel

ampel1 = ampel.Ampel()
ampel2 = ampel.Ampel()
ampel3 = ampel.Ampel()
ampel4 = ampel.Ampel()

def simulation():
    ampel1.setLampen(True,False,False)
    ampel3.setLampen(True,False,False)
    ampel2.setLampen(False,False,True)
    ampel4.setLampen(False,False,True)
    print("Aktueller status:\n")
    print("Ampel1: " + str(ampel1.gibAus()))
    print("Ampel2: " + str(ampel2.gibAus()))
    print("Ampel3: " + str(ampel3.gibAus()))
    print("Ampel4: " + str(ampel4.gibAus()))
    ampel1.schalten()
    ampel2.schalten()
    ampel3.schalten()
    ampel4.schalten()
    print("Aktueller status:\n")
    print("Ampel1: " + str(ampel1.gibAus()))
    print("Ampel2: " + str(ampel2.gibAus()))
    print("Ampel3: " + str(ampel3.gibAus()))
    print("Ampel4: " + str(ampel4.gibAus()))
    ampel1.schalten()
    ampel2.schalten()
    ampel3.schalten()
    ampel4.schalten()
    print("Aktueller status:\n")
    print("Ampel1: " + str(ampel1.gibAus()))
    print("Ampel2: " + str(ampel2.gibAus()))
    print("Ampel3: " + str(ampel3.gibAus()))
    print("Ampel4: " + str(ampel4.gibAus()))
    ampel1.schalten()
    ampel2.schalten()
    ampel3.schalten()
    ampel4.schalten()
    print("Aktueller status:\n")
    print("Ampel1: " + str(ampel1.gibAus()))
    print("Ampel2: " + str(ampel2.gibAus()))
    print("Ampel3: " + str(ampel3.gibAus()))
    print("Ampel4: " + str(ampel4.gibAus()))
    ampel1.schalten()
    ampel2.schalten()
    ampel3.schalten()
    ampel4.schalten()
    print("Aktueller status:\n")
    print("Ampel1: " + str(ampel1.gibAus()))
    print("Ampel2: " + str(ampel2.gibAus()))
    print("Ampel3: " + str(ampel3.gibAus()))
    print("Ampel4: " + str(ampel4.gibAus()))
    ampel1.schalten()
    ampel2.schalten()
    ampel3.schalten()
    ampel4.schalten()


simulation()
